### ISSUE TITLE
드롭아웃에서 에러 문의드립니다.

### ISSUE THREAD

**Issue by Biyong-Jeong** [DNRY/dlopt#5]
안녕하세요.
또 문의가 있어 글 남깁니다.

392페이지의 예제를 실행하였는데 하기 그림과 같은 에러가 발생하였는데
어떤 문제인지 문의드리려 합니다.

github에 있는 코드와 비교해도 오탈자는 없는 것 같은데
실행이 안되는 이유 문의드립니다.

바쁘실텐데 확인 부탁드립니다.

![스크린샷 2020-06-23 오후 3 43 02](https://user-images.githubusercontent.com/51958475/85369820-c1bf7e00-b568-11ea-97d3-bf0e35232b8f.png)

**Comment by yhbyhb** [comment]
안녕하세요. 
안타깝게도 392페이지의 코드만으로는 위와 같은 에러를 똑같이 만들 수가 없었습니다.
에러의 내용으로 원인을 유추해 본다면, 학습을 시키기 위해서 넣어줘야 할 데이터들을 넣어주지 못한것으로 보입니다.

392페이지 코드를 실행시키기 위해서는 다음과 같은 코드 블럭들이 필요합니다.
- 학습 및 테스트를 위한 데이터 준비
  - p364
  - p365 첫번째 코드 블럭 
- 하이퍼 파라메터 설정
  - p390
  - p391 두번째 코드 블럭
- 신경망 모델 구성
  - p391 첫번째 코드 블럭

아래에 코드 전체를 실행하면 에러없이 예제를 실행 할 수 있을 것 입니다.

```python
import numpy as np
import matplotlib.pylab as plt
import tensorflow as tf
%matplotlib inline

# 시각화를 위한 함수
def visualize_l2(pred, x_train, y_train, x_test, y_test):
    from matplotlib.patches import Rectangle
    plt.plot(x_train, y_train, '.k', markerfacecolor='none', label='Train Data')
    plt.plot(x_train, pred,  '--k', label='Model')
    plt.plot(x_test, y_test, 'xk', markersize=3, markerfacecolor='none', label='Test Data')
    currentAxis = plt.gca()
    for k, (xx,yy) in enumerate(zip(x_train, y_train)):
        error = pred[k] - yy
        currentAxis.add_patch(Rectangle((xx, yy), 
                                        error, error,
                              alpha=0.1, facecolor='gray', edgecolor='k'))
    plt.grid()
    plt.axis('equal')
    plt.xlabel('x')
    plt.ylabel('y')

# p364
# 학습용 데이터 생성
np.random.seed(327)
x_train = np.linspace(-1,1,50)
y_train = x_train**3 + 0.1 * x_train**2 -0.15 * x_train + 1.0 + 0.5 * np.random.rand(len(x_train))

# 테스트용 데이터 생성
x_test = np.linspace(-1,1,50)
y_test = x_test**3 + 0.1 * x_test**2 -0.15 * x_test + 1.0 + 0.5 * np.random.rand(len(x_test))

# p365 첫번째 코드 블럭
# 특성값
features_train = np.array([[xval] for xval in x_train])
labels_train = y_train.reshape(-1, 1)

features_test = np.array([[xval] for xval in x_test])
labels_test = y_test.reshape(-1, 1)

# p390
keep_probability = tf.placeholder(tf.float32)
num_hidden1 = 10
num_hidden2 = 5

# p391
# 입력층
x = tf.placeholder(tf.float32, shape=[None, 1])

rand_init = tf.random_normal_initializer(seed=624)
# 은닉층 1
hidden1 =  tf.contrib.layers.fully_connected(x, num_hidden1,
                                          activation_fn=tf.nn.sigmoid,
                                          weights_initializer=rand_init,
                                          biases_initializer=rand_init)
# 드랍아웃 1
hidden1 = tf.contrib.layers.dropout(hidden1, keep_prob=keep_probability, seed=848)

# 은닉층 2
hidden2 =  tf.contrib.layers.fully_connected(hidden1, num_hidden2,
                                          activation_fn=tf.nn.sigmoid,
                                          weights_initializer=rand_init,
                                          biases_initializer=rand_init)
# 드랍아웃 2
hidden2 = tf.contrib.layers.dropout(hidden2, keep_prob=keep_probability, seed=848)


# 출력층
yhat =  tf.contrib.layers.fully_connected(hidden2, 1,
                                          activation_fn=None,
                                          weights_initializer=rand_init,
                                          biases_initializer=rand_init)

# 손실함수
y = tf.placeholder(tf.float32, shape=[None, 1])
loss = tf.losses.mean_squared_error(y, yhat)

# 수치최적화 알고리즘
MaxEpoch = 4000
lr = 0.1
batch_size = 10
optimizer = tf.train.AdamOptimizer(lr)
train = optimizer.minimize(loss)

# p392
# 데이터 섞기
np.random.seed(320)
shuffled_id = np.arange(0, len(x_train))
np.random.shuffle(shuffled_id)
shuffled_x_train = features_train[shuffled_id]
shuffled_y_train = labels_train[shuffled_id]

# 손실함수 기록용 변수
loss_train_history = []
loss_test_history = []

# 스토캐스틱 방법
from helper import generate_batches
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(MaxEpoch+1):
        for x_batch, y_batch in generate_batches(batch_size, shuffled_x_train, shuffled_y_train):
            sess.run(train, feed_dict={x:x_batch, y:y_batch, keep_probability: 0.85})

        loss_train = sess.run(loss, feed_dict={x:features_train, y:labels_train, keep_probability: 1.0})
        loss_test = sess.run(loss, feed_dict={x:features_test, y:labels_test, keep_probability: 1.0})
        loss_train_history.append(loss_train)
        loss_test_history.append(loss_test)
    
        # 책에 없는 plot 용 코드
        if epoch in [30, 100, 1000, 3000, 4000]:
            loss_val_train, pred = sess.run([loss, yhat], feed_dict={x:features_train, y:labels_train, keep_probability: 1.0})
            loss_val_test, pred = sess.run([loss, yhat], feed_dict={x:features_test, y:labels_test, keep_probability: 1.0})
            plt.title("loss = ({:1.3f}, {:1.3f}) \n at Epoch {}".format(loss_val_train, loss_val_test, epoch))
            visualize_l2(pred, x_train, y_train, x_test, y_test)
            plt.show()
```

**Comment by Biyong-Jeong** [comment]
다음과 같이 진행해 보았는데도 동일한 에러 현상이 발생하네요...
처음에 오탈자나 다른 문제가 있으면 수정해서 다시 돌리면 항상 이런 문제가 나오는 것 같아
쥬피터 노트북 셧다운 하고 다시 오픈해도 동일한 현상이 발생합니다.
일전에도 다른 예제 하다가 비슷한 현상이 있었는데 제 컴퓨터의 환경이나 뭐가 문제가 있는건지...
도통 알 수가 없습니다..

```
`#드롭아웃을 이용한 오버피팅된 신경망 모델

import numpy as np
import tensorflow as tf
import matplotlib.pylab as plt
%matplotlib inline


# 시각화를 위한 함수
def visualize_l2(pred, x_train, y_train, x_test, y_test):
    from matplotlib.patches import Rectangle
    plt.plot(x_train, y_train, '.k', markerfacecolor='none', label='Train Data')
    plt.plot(x_train, pred,  '--k', label='Model')
    plt.plot(x_test, y_test, 'xk', markersize=3, markerfacecolor='none', label='Test Data')
    currentAxis = plt.gca()
    for k, (xx,yy) in enumerate(zip(x_train, y_train)):
        error = pred[k] - yy
        currentAxis.add_patch(Rectangle((xx, yy), 
                                        error, error,
                              alpha=0.1, facecolor='gray', edgecolor='k'))
    plt.grid()
    plt.axis('equal')
    plt.xlabel('x')
    plt.ylabel('y')
    

def generate_batches(batch_size, features, labels):
    outout_batches = []
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        outout_batches.append(batch)
    return outout_batches
    

#학습용 데이터 생성
np.random.seed(327)
x_train = np.linspace(-1,1,50)
y_train = x_train**3 +0.1*x_train**2-0.15*x_train + 1.0 +0.5*np.random.rand(len(x_train))

#테스트용 데이터 생성
x_test = np.linspace(-1, 1, 50)
y_test = x_test**3 +0.1*x_test**2 -0.15*x_test +1.0 +0.5*np.random.rand(len(x_test))

#특성값(신경망 모델이용하므로 입력 데이터 그대로 사용)
features_train = np.array([[xval] for xval in x_train])
labels_train = y_train.reshape(-1,1)

features_test = np.array([[xval] for xval in x_test])
labels_test = y_test.reshape(-1,1)

#은닉층들의 노드 개수
keep_probability = tf.placeholder(tf.float32) # placeholder선언 이유는 모델 예측값을 구하거나 정확도를 구할 때 1.0을 넣기 위하여
num_hidden1 = 10
num_hidden2 = 5

rand_init = tf.random_normal_initializer(seed=624)

# 입력층
x = tf.placeholder(tf.float32, shape=[None, 1])

#은닉층1
hidden1 = tf.contrib.layers.fully_connected(x, num_hidden1,
                                           activation_fn=tf.nn.sigmoid,
                                           weights_initializer=rand_init,
                                           biases_initializer=rand_init)

#드롭아웃1
hidden1 = tf.contrib.layers.dropout(hidden1, keep_prob=keep_probability, seed=848)

#은닉층2
hidden2 = tf.contrib.layers.fully_connected(hidden1, num_hidden2,
                                           activation_fn = tf.nn.sigmoid,
                                           weights_initializer=rand_init,
                                           biases_initializer=rand_init)
#드롭아웃2
hidden2 = tf.contrib.layers.dropout(hidden2, keep_prob=keep_probability, seed=848)

#출력층
yhat = tf.contrib.layers.fully_connected(hidden2,1,
                                        activation_fn=None,
                                        weights_initializer=rand_init,
                                        biases_initializer=rand_init)


#손실함수
y = tf.placeholder(tf.float32, shape=[None,1])
loss = tf.losses.mean_squared_error(y, yhat)

#수치최적화 알고리즘
MaxEpochs = 4000
lr = 0.1
batch_size = 10
optimizer = tf.train.AdamOptimizer(lr)
train = optimizer.minimize(loss)

#데이터 섞기
np.random.seed(320)
shuffled_id = np.arange(0, len(x_train))
np.random.shuffle(shuffled_id)
shuffled_x_train = features_train[shuffled_id]
shuffled_y_train = labels_train[shuffled_id]

#손실함수 기록용 변수
loss_train_history=[]
loss_test_history=[]

#스토캐스틱 방법
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for epoch in range(MaxEpochs+1):
        for x_batch, y_batch in generate_batches(batch_size,
                                                shuffled_x_train,
                                                shuffled_y_train):
            sess.run(train, feed_dict={x:x_batch, y:y_batch, keep_probability:0.85}) # train부분만 0.85 나머지는 1.0
        loss_train = sess.run(loss, feed_dict={x:features_train, y:labels_train, keep_probability:1.0})
        loss_test = sess.run(loss, feed_dict={x:features_test, y:labels_test, keep_probability:1.0})
        loss_train_history.append(loss_train)
        loss_test_history.append(loss_test)
        
        if epoch in [30, 100, 1000, 3000, 4000]:
            loss_val_train, pred = sess.run([loss, yhat], feed_dict={x:features_train, y:labels_train})
            loss_val_test, pred = sess.run([loss, yhat], feed_dict={x:features_test, y:labels_test})
            plt.title("loss = ({:1.3f}, {:1.3f}) \n at Epoch {}".format(loss_val_train, loss_val_test, epoch))
            visualize_l2(pred, x_train, y_train, x_test, y_test)
            plt.show()
    
    final_loss, pred = sess.run([loss, yhat], feed_dict={x:features_train, y:labels_train})

plt.title("loss = {:1.3f} (lr: {:1.3E})".format(final_loss, lr))
visualize_l2(pred, x_train, y_train, x_test, y_test)
plt.show()`
```

에러 메시지
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1277     try:
-> 1278       return fn(*args)
   1279     except errors.OpError as e:

/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1262       return self._call_tf_sessionrun(
-> 1263           options, feed_dict, fetch_list, target_list, run_metadata)
   1264 

/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1349         self._session, options, feed_dict, fetch_list, target_list,
-> 1350         run_metadata)
   1351 

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-b1f70bfea952> in <module>()
    122 
    123         if epoch in [30, 100, 1000, 3000, 4000]:
--> 124             loss_val_train, pred = sess.run([loss, yhat], feed_dict={x:features_train, y:labels_train})
    125             loss_val_test, pred = sess.run([loss, yhat], feed_dict={x:features_test, y:labels_test})
    126             plt.title("loss = ({:1.3f}, {:1.3f}) \n at Epoch {}".format(loss_val_train, loss_val_test, epoch))

/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    875     try:
    876       result = self._run(None, fetches, feed_dict, options_ptr,
--> 877                          run_metadata_ptr)
    878       if run_metadata:
    879         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1098     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1099       results = self._do_run(handle, final_targets, final_fetches,
-> 1100                              feed_dict_tensor, options, run_metadata)
   1101     else:
   1102       results = []

/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1270     if handle is None:
   1271       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1272                            run_metadata)
   1273     else:
   1274       return self._do_call(_prun_fn, handle, feeds, fetches)

/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1289         except KeyError:
   1290           pass
-> 1291       raise type(e)(node_def, op, message)
   1292 
   1293   def _extend_graph(self):

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/asyncio/base_events.py", line 1425, in _run_once
    handle._run()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-b1f70bfea952>", line 54, in <module>
    keep_probability = tf.placeholder(tf.float32) # placeholder선언 이유는 모델 예측값을 구하거나 정확도를 구할 때 1.0을 넣기 위하여
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1735, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4925, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/Users/jeongbiyong/anaconda3/envs/deep-learning/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by yhbyhb** [comment]
코드를 올려주셔서 문제를 쉽게 찾을 수 있었습니다.
드롭아웃의 경우에는 loss를 구하실 때 keep_probability 를 1.0 으로 넣어야 하는데 없어서 문제가 생겼습니다.
아래와 비슷하게 validation 의 training loss 와 test loss, 최종 loss 를 구할 때 feed_dict 에 keep_probaility를 넣어주시면 문제 없을 것 입니다.
```python
feed_dict={x:features_train, y:labels_train})
```

```python
feed_dict={x:features_train, y:labels_train, keep_probability: 1.0})
```

**Comment by Biyong-Jeong** [comment]
드디어... 정상적으로 실행되었습니다.
감사합니다.
git-hub의 코드 중간에 참조해가면서 했는데
해당 부분은 제가 임의로 하다가 놓쳤고 비교 안하고 해서 그랬나 봅니다.

그 순간은 너무 짜증이 나고 답답하지만
늘 신기하고 흥미롭습니다.  자그마한 실수가 에러를 일으키는 이런 것들이 말입니다.

해당 건은 잘 마무리 되었습니다.
다시 한 번 감사드립니다.^^

**Comment by yhbyhb** [comment]
정상적으로 실행되어서 다행입니다.
간단한 실수가 코드를 만든 본인에게는 순간적으로 잘 안보이기도 합니다.
하루 쯤 지나고 코드를 다시 한번 보는 방법이나, 코드 비교툴을 사용해서, 잘되는것과 잘안되는것을 비교하는것도 하나의 추천하는 방법입니다.
감사합니다.
